### ISSUE TITLE
iPad Version?

### ISSUE THREAD

**Issue by K232** [sthewissen/Coffeeffee#1]
Hi Steven,
great job, thanks for this design!! But the skiasharp at the bottom doesn't look very nice on iPads. Any idea how to fix it? Of course it's fine to close this issue as it's just a demo, but maybe it's just a small fix for you, I don't know,
Many thanks!
![iPad Pro (12 9-inch) (4th generation) (13 5) 2020-05-28 07-27-31](https://user-images.githubusercontent.com/685016/83102640-3cee5b00-a0b5-11ea-920b-15d9fa8eeb8d.jpg)

**Comment by sthewissen** [comment]
This is probably due to the fact that I was using a predefined path that uses fixed values for where the points are. The solution is probably to draw the path based on the current screen width instead, meaning that the curves will always match the correct width. In the current implementation that isn't really that simple to fix :(

**Comment by K232** [comment]
OK, no problem, thanks for fast reply!
